twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        # Mailer
        # point this wherever your images live
        '%images%': images
        # point this wherever your css files live
        '%styles%': styles