controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

tag:
    resource: ../../src/Api/
    type: annotation
    prefix: /tags

kernel:
    resource: ../../src/Kernel.php
    type: annotation
