controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    schemes: [https]
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

api:
    resource: ../../src/Api/
    type: annotation
    prefix: /api
    schemes: [https]

kernel:
    resource: ../../src/Kernel.php
    type: annotation
